/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LiikmedImport } from './routes/liikmed'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMenuImport } from './routes/_authenticated/menu'
import { Route as AuthenticatedEventsImport } from './routes/_authenticated/events'
import { Route as AuthenticatedAdminImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedEventBattleshipBingoEventIdImport } from './routes/_authenticated/event/battleship-bingo.$eventId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LiikmedRoute = LiikmedImport.update({
  path: '/liikmed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedMenuRoute = AuthenticatedMenuImport.update({
  path: '/menu',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedEventsRoute = AuthenticatedEventsImport.update({
  path: '/events',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAdminRoute = AuthenticatedAdminImport.update({
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedEventBattleshipBingoEventIdRoute =
  AuthenticatedEventBattleshipBingoEventIdImport.update({
    path: '/event/battleship-bingo/$eventId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/liikmed': {
      id: '/liikmed'
      path: '/liikmed'
      fullPath: '/liikmed'
      preLoaderRoute: typeof LiikmedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/event/battleship-bingo/$eventId': {
      id: '/_authenticated/event/battleship-bingo/$eventId'
      path: '/event/battleship-bingo/$eventId'
      fullPath: '/event/battleship-bingo/$eventId'
      preLoaderRoute: typeof AuthenticatedEventBattleshipBingoEventIdImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LiikmedRoute,
  LoginRoute,
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedAdminRoute,
    AuthenticatedEventsRoute,
    AuthenticatedMenuRoute,
    AuthenticatedProfileRoute,
    AuthenticatedEventBattleshipBingoEventIdRoute,
  }),
})

/* prettier-ignore-end */

